package com.surveyvor.pdf;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.surveyvor.model.User;

/**
 * A Spring controller that allows the users to download a PDF document
 * generated by the iText library.
 *
 * @author www.codejava.net
 *
 */
@Controller
public class PdfController {

	/**
	 * Handle request to download a PDF document
	 */
	@RequestMapping(value = "/downloadPDF", method = RequestMethod.GET)
	public ModelAndView downloadPDF() {
		//get Map<Long,List<User>> result from algorithm
		Map<Long,List<User>> resultat = new HashMap<Long,List<User>>();

		//dummy data for Map

		//groupe1
		User usr = new User();
		User usr2 = new User();
		User usr3 = new User();
		List<User> list= new ArrayList<User>();
		usr.setName("laurent");
		usr2.setName("laurent2");
		usr3.setName("laurent3");

		list.add(usr);
		list.add(usr2);
		list.add(usr3);

		resultat.put((long) 1,list);

		//groupe2
		User usrbis = new User();
		User usrbis2 = new User();
		User usrbis3 = new User();
		List<User> listbis= new ArrayList<User>();
		usrbis.setName("test");
		usrbis2.setName("test2");
		usrbis3.setName("test3");

		listbis.add(usrbis);
		listbis.add(usrbis2);
		listbis.add(usrbis3);

		resultat.put((long) 2,listbis);

		//TODO recuperer la Map<Long,List<User>> résultat de l'algorithme
		
		// return a view which will be resolved by an PDF view resolver
		return new ModelAndView("pdfView", "resultat", resultat);
	}
}